/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <opencv2/opencv.hpp>


using namespace cv;
using namespace std;
/* Header for class opencvdemo_com_ndkopencvtest_opencvNativeClass */

#ifndef _Included_opencvdemo_com_ndkopencvtest_opencvNativeClass
#define _Included_opencvdemo_com_ndkopencvtest_opencvNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     opencvdemo_com_ndkopencvtest_opencvNativeClass
 * Method:    convertGray
 * Signature: (JJ)I
 */
 int toGray(Mat img, Mat& gray);
JNIEXPORT jint JNICALL Java_opencvdemo_com_ndkopencvtest_opencvNativeClass_convertGray
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
